USE ROLE ACCOUNTADMIN;

CREATE ROLE doom_role;

CREATE DATABASE IF NOT EXISTS doom_db;
GRANT OWNERSHIP ON DATABASE doom_db TO ROLE doom_role;

CREATE OR REPLACE WAREHOUSE doom_wh WITH
  WAREHOUSE_SIZE='X-SMALL';
GRANT USAGE ON WAREHOUSE doom_wh TO ROLE doom_role;

CREATE SECURITY INTEGRATION IF NOT EXISTS doom_snowservices_ingress_oauth
  TYPE=oauth
  OAUTH_CLIENT=snowservices_ingress
  ENABLED=true;

GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE doom_role;

CREATE COMPUTE POOL doom_compute_pool
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS;
GRANT USAGE, MONITOR ON COMPUTE POOL doom_compute_pool TO ROLE doom_role;

GRANT ROLE doom_role TO USER <your_user>;

USE ROLE doom_role;
USE DATABASE doom_db;
USE WAREHOUSE doom_wh;

CREATE SCHEMA IF NOT EXISTS doom_schema;
CREATE IMAGE REPOSITORY IF NOT EXISTS doom_repository;


SHOW COMPUTE POOLS;
SHOW WAREHOUSES;
SHOW IMAGE REPOSITORIES;
